plugins {
    id 'com.android.application'
}

android {
    namespace 'app.openpencil.bleuploader'
    compileSdk 35

    defaultConfig {
        applicationId 'app.openpencil.bleuploader'
        minSdk 26
        targetSdk 35
        versionCode 14
        versionName '0.5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
